# Generated by Django 3.1.5 on 2021-01-08 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=10000, null=True,
                                          verbose_name='Инфо о кабинете')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(
                    verbose_name='Дата начала бронирования')),
                ('date_to', models.DateTimeField(
                    verbose_name='Дата окончание бронирования')),
                ('tenant_info', models.CharField(max_length=10000,
                                                 verbose_name='Инфо о бронировании')),
                ('office',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='booking', to='api.office',
                                   verbose_name='Кабинет')),
                ('tenant_name',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='booking',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Бронирующий')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Бронь',
            },
        ),
    ]
