# Generated by Django 3.1.5 on 2021-01-09 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='tenant_name',
            new_name='owner',
        ),
    ]
